### ISSUE TITLE
Some legacy redirects are broken

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-archive#452]
This might be a missing-data issue, but in any case archive should be more robust to bad urls.

`https://cnx.org/content/m31913/1.5/?collection=col11120/1.4`

Causes this traceback:

``` pytb
ERROR:waitress:Exception when serving /content/m31913/latest/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.9-py2.7.egg/waitress/channel.py", line 337, in service
    task.service()
  File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.4-py2.7.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.4-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.4-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.4-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.4-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/usr/local/lib/python2.7/dist-packages/cnx_archive-2.5.1-py2.7.egg/cnxarchive/views.py", line 564, in redirect_legacy_content
    _get_page_in_book(id, version, book_uuid, book_version)
  File "/usr/local/lib/python2.7/dist-packages/cnx_archive-2.5.1-py2.7.egg/cnxarchive/views.py", line 264, in _get_page_in_book
    pages = list(flatten_tree_to_ident_hashes(coltree))
  File "/usr/local/lib/python2.7/dist-packages/cnx_epub-0.8.0-py2.7.egg/cnxepub/models.py", line 110, in flatten_tree_to_ident_hashes
    if 'contents' in item_or_tree:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by reedstrm** [comment]
grr, forgot best markup for back traces. This is probably missing tree data for version 1.4 of the collection, since changing it to `1.7` or `latest` or leaving it off completely, works.

**Comment by kerwinso** [comment]
collxml for version 1.4 does not exist. Because of that, the tree (aka TOC) associated with that version of the collection does not exist. @pumazi and I determined that this is not a python issue, we will look into adding some better exception handling.

**Comment by edwoodward** [comment]
This has been fixed. Closing
