### ISSUE TITLE
Data error when returning contents

### ISSUE THREAD

**Issue by karenc** [Connexions/cnx-archive#507]
When trying to go to https://qa.cnx.org/contents/d50f6e32-0fda-46ef-a362-9bd36ca7c97d, we get a "Oops!  Unknown Error" page.  The traceback for archive:

```
ERROR:waitress:Exception when serving /contents/d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24.json
Traceback (most recent call last):
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/router.py", line 233, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/router.py", line 208, in invoke_subrequest
    response = handle_request(request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 409, in viewresult_to_response
    result = view(context, request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/var/cnx/venvs/archive/src/cnx-archive/cnxarchive/views/content.py", line 207, in get_content_json
    result = _get_content_json()
  File "/var/cnx/venvs/archive/src/cnx-archive/cnxarchive/views/content.py", line 85, in _get_content_json
    result['tree'] = get_tree(ident_hash, cursor)
  File "/var/cnx/venvs/archive/src/cnx-archive/cnxarchive/database.py", line 113, in get_tree
    (uuid, version, as_collated,))
DataError: invalid input syntax for type json
DETAIL:  Expected end of input, but found ",".
CONTEXT:  JSON data, line 1: ...g_a@5.24","title":"University Physics Volume 1"},
```

**Comment by karenc** [comment]
I had a look at what `tree_to_json` was returning and...

```
repository=# select tree_to_json('d50f6e32-0fda-46ef-a362-9bd36ca7c97d', '5.24', FALSE);
                                                                    tree_to_json                                                                     
-----------------------------------------------------------------------------------------------------------------------------------------------------
 {"id":"d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24","shortId":"1Q9uMg_a@5.24","title":"University Physics Volume 1"},                                +
 {"id":"d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24","shortId":"1Q9uMg_a@5.24","title":"University Physics Volume 1"},                                +
 {"id":"d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24","shortId":"1Q9uMg_a@5.24","title":"University Physics Volume 1"},                                +
 {"id":"d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24","shortId":"1Q9uMg_a@5.24","title":"University Physics Volume 1"},                                +
 {"id":"d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24","shortId":"1Q9uMg_a@5.24","title":"University Physics Volume 1"},                                +
 {"id":"d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24","shortId":"1Q9uMg_a@5.24","title":"University Physics Volume 1"},                                +
 {"id":"d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24","shortId":"1Q9uMg_a@5.24","title":"University Physics Volume 1", "contents":[                    +
     {"id":"1a87e4af-d3b2-4c23-981c-d33ca2fed9b2@8","shortId":"Gofkr9Oy@8","title":"Preface"},                                                      +
     {"id":"1a87e4af-d3b2-4c23-981c-d33ca2fed9b2@8","shortId":"Gofkr9Oy@8","title":"Preface"},                                                      +
     {"id":"1a87e4af-d3b2-4c23-981c-d33ca2fed9b2@8","shortId":"Gofkr9Oy@8","title":"Preface"},                                                      +
     {"id":"1a87e4af-d3b2-4c23-981c-d33ca2fed9b2@8","shortId":"Gofkr9Oy@8","title":"Preface"},                                                      +
     {"id":"1a87e4af-d3b2-4c23-981c-d33ca2fed9b2@8","shortId":"Gofkr9Oy@8","title":"Preface"},                                                      +
     {"id":"1a87e4af-d3b2-4c23-981c-d33ca2fed9b2@8","shortId":"Gofkr9Oy@8","title":"Preface"},                                                      +
     {"id":"1a87e4af-d3b2-4c23-981c-d33ca2fed9b2@8","shortId":"Gofkr9Oy@8","title":"Preface"},                                                      +
     {"id":"subcol","shortId":"subcol","title":"Unit 1. Mechanics", "contents":[]},                                                                 +
     {"id":"subcol","shortId":"subcol","title":"Unit 1. Mechanics", "contents":[]},                                                                 +
     {"id":"subcol","shortId":"subcol","title":"Unit 1. Mechanics", "contents":[]},                                                                 +
     {"id":"subcol","shortId":"subcol","title":"Unit 1. Mechanics", "contents":[]},                                                                 +
     {"id":"subcol","shortId":"subcol","title":"Unit 1. Mechanics", "contents":[]},                                                                 +
     {"id":"subcol","shortId":"subcol","title":"Unit 1. Mechanics", "contents":[]},                                                                 +
     {"id":"subcol","shortId":"subcol","title":"Unit 1. Mechanics", "contents":[                                                                    +
         {"id":"subcol","shortId":"subcol","title":"Units and Measurement", "contents":[]},                                                         +
         {"id":"subcol","shortId":"subcol","title":"Units and Measurement", "contents":[]},                                                         +
         {"id":"subcol","shortId":"subcol","title":"Units and Measurement", "contents":[]},                                                         +
         {"id":"subcol","shortId":"subcol","title":"Units and Measurement", "contents":[]},                                                         +
         {"id":"subcol","shortId":"subcol","title":"Units and Measurement", "contents":[]},                                                         +
...

repository=# select count(*) from modules where uuid = 'd50f6e32-0fda-46ef-a362-9bd36ca7c97d' and major_version = 5 and minor_version = 24;
 count 
-------
     7
(1 row)

repository=# select count(*) from modules where uuid = 'd50f6e32-0fda-46ef-a362-9bd36ca7c97d' and major_version = 5 and minor_version = 23;
 count 
-------
     1
(1 row)


```

We shouldn't be getting multiple rows in the table for one version of a book.  The last version (5.23) was still correct, but 5.24 has 7 copies.

**Comment by karenc** [comment]
I tried deleting the extra rows in the database.

```
repository=# select module_ident, uuid || '@' || module_version(major_version, minor_version) as ident_hash from modules where uuid = 'd50f6e32-0fda-46ef-a362-9bd36ca7c97d' and major_version = 5 and minor_version = 24 order by module_ident;
 module_ident |                ident_hash                 
--------------+-------------------------------------------
       198938 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24
       198944 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24
       198950 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24
       198956 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24
       198961 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24
       198968 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24
       198975 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24
(7 rows)

repository=# delete from modules where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);                                                                      ERROR:  update or delete on table "modules" violates foreign key constraint "module_files_module_ident_fkey" on table "module_files"
DETAIL:  Key (module_ident)=(198938) is still referenced from table "module_files".
repository=# select * from module_files where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
 module_ident | fileid  |  filename
--------------+---------+-------------
       198938 | 1033713 | ruleset.css
       198944 | 1022485 | ruleset.css
       198950 | 1022485 | ruleset.css
       198956 | 1022485 | ruleset.css
       198961 | 1022485 | ruleset.css
       198968 | 1022485 | ruleset.css
(6 rows)     
             
repository=# delete from module_files where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
DELETE 6     
repository=# delete from modules where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
ERROR:  update or delete on table "modules" violates foreign key constraint "moduletags_module_ident_fkey" on table "moduletags"
DETAIL:  Key (module_ident)=(198938) is still referenced from table "moduletags".
repository=# select * from moduletags where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
 module_ident | tagid
--------------+-------
       198938 |     8
       198944 |     8
       198950 |     8
       198956 |     8
       198961 |     8
       198968 |     8
(6 rows)     
             
repository=# delete from moduletags where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
DELETE 6     
repository=# delete from modules where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
ERROR:  update or delete on table "modules" violates foreign key constraint "document_baking_result_associations_module_ident_fkey" on table "document_baking_result_associations"         
DETAIL:  Key (module_ident)=(198938) is still referenced from table "document_baking_result_associations".
repository=# select * from document_baking_result_associations where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
 module_ident |              result_id               |            created
--------------+--------------------------------------+-------------------------------
       198938 | f6323933-94bd-48b0-a4a2-e9dcdccf701a | 2017-07-28 15:27:52.966196-05
       198938 | da4bb294-c0c7-4577-b160-eca058e14720 | 2017-07-28 15:27:53.064679-05
       198944 | 5dd3d6b4-1f4d-42a4-a161-a9aa65345739 | 2017-07-28 15:29:33.094306-05
       198944 | 68fae516-7e93-4972-9f94-ca10cdb678ea | 2017-07-28 15:29:33.156655-05
       198950 | ba9b1530-937e-4c69-ac34-8d59176951b5 | 2017-07-28 15:30:58.548686-05
       198950 | ce483257-1323-46d8-a27e-cf63a3f2e6b7 | 2017-07-28 15:30:58.606099-05
       198956 | 8ea1ebad-ee5c-460d-ba95-3166a8ce2f03 | 2017-07-28 15:32:36.056447-05
       198956 | b48675a8-d26c-46e4-9b65-8162ad1a82f8 | 2017-07-28 15:32:36.122764-05
       198961 | a23e7ac1-819a-444e-b203-da2b52dcceee | 2017-07-28 15:33:44.214859-05
       198961 | ba80b7e4-0958-4727-a591-3df01c9cd001 | 2017-07-28 15:33:44.259205-05
       198968 | c3600eb4-abbe-46aa-ae9a-8cffa4bced32 | 2017-07-28 15:35:03.780639-05
       198968 | 306c2082-a5bb-4e95-bf7d-8deb38e5452a | 2017-07-28 15:35:03.858444-05
       198938 | aa4aecf4-2279-4f2a-a205-97744960d31f | 2017-07-28 15:46:53.970328-05
(13 rows)    
             
repository=# delete from document_baking_result_associations where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
DELETE 13
repository=# delete from modules where module_ident in (198938, 198944, 198950, 198956, 198961, 198968);
DELETE 6

```

This appears to fix https://qa.cnx.org/contents/d50f6e32-0fda-46ef-a362-9bd36ca7c97d.

**Comment by karenc** [comment]
The `latest_modules` table was still showing `5.23` as the latest version, so I updated it:

```
repository=# select revised, module_ident, uuid || '@' || module_version(major_version, minor_version) as ident_hash, moduleid from latest_modules where uuid = 'd50f6e32-0fda-46ef-a362-9bd36ca7c97d' and major_version = 5;
            revised            | module_ident |                ident_hash                 | moduleid
-------------------------------+--------------+-------------------------------------------+----------
 2017-07-28 13:35:22.774896-05 |       198895 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.23 | col12031
(1 row)
repository=# select revised, module_ident, uuid || '@' || module_version(major_version, minor_version) as ident_hash from modules where uuid = 'd50f6e32-0fda-46ef-a362-9bd36ca7c97d' and major_version = 5 and minor_version = 24;
            revised            | module_ident |                ident_hash
-------------------------------+--------------+-------------------------------------------
 2017-07-28 15:36:06.251221-05 |       198975 | d50f6e32-0fda-46ef-a362-9bd36ca7c97d@5.24
(1 row)

repository=# delete from latest_modules where moduleid = 'col12031' or uuid = 'd50f6e32-0fda-46ef-a362-9bd36ca7c97d';
DELETE 1
repository=# insert into latest_modules (                                                                                                                
                uuid, module_ident, portal_type, moduleid, version, name,
                created, revised, abstractid, stateid, doctype, licenseid,
                submitter,submitlog, parent, language,
                authors, maintainers, licensors, parentauthors, google_analytics,
                major_version, minor_version, print_style, baked, recipe)
select                 uuid, module_ident, portal_type, moduleid, version, name,
                created, revised, abstractid, stateid, doctype, licenseid,
                submitter,submitlog, parent, language,
                authors, maintainers, licensors, parentauthors, google_analytics,
                major_version, minor_version, print_style, baked, recipe
from modules where module_ident = 198975;
INSERT 0 1
```

**Comment by karenc** [comment]
The real issue is in #508.

**Comment by karenc** [comment]
The script to remove duplicate copies is here: https://github.com/Connexions/devops/blob/master/scripts/remove_duplicate_minor_version_books.py

**Comment by karenc** [comment]
The ansible playbook is here: https://github.com/Connexions/cnx-deploy/pull/354
